algoritmo "resultado"
// Função : obter como resultado do dobro e o triplo do numero digitado
// Autor :  Sarah
// Data : 29/03/2022
var
numero,dobro,triplo:real

inicio
//entrada
escreval("digite um numero")
leia(numero)
escreval("digite o dobro de um numero")
leia(dobro)
escreval("digite o triplo de um numero")
leia(triplo)


//processamento
numero <-(dobro*triplo)

//saida
limpatela
escreval("o resultado do dobro e de um triplo de um numero",numero)

fimalgoritmo
