algoritmo "semnome"
// Função :
// Autor :
// Data : 29/03/2022
// Seção de Declarações 
var
 salario,porc,aumento,total:real
inicio
// entrada
escreval(" Digite seu salario",salario)
leia(salario)
escreval(" Digite a porcentagem do seu aumento")
leia(porc)
//processamento
aumento <-(salario*porc/100)
total<-(aumento+salario)

escreval(" O seu salario aumentou de:R$",aumento,"00")



fimalgoritmo
